# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 719948270da7a1f24e10d316edc7e083a97f07766ba4e516db5a4db702f22c62aa87ffe683f33ee28a6567106a33c0457f11e39cbd166e782f885a37e1ae05a2

test:
  secret_key_base: 6d31259818f4da34e4e5a831135b3d8ceb69496633ba3c28c97aa17a6c3c09506322f951592063bd927316968518d634fa7fc53498f95b92911193fc9f6aee94

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
